#!/usr/bin/env bash

mv /app/disable-warnings.py /app/.ipython/profile_default/startup/disable-warnings.py

pgcontents init -l $DATABASE_URL --no-prompt

export PYTHONPATH=$PYTHONPATH:'/app'

jupyter notebook \
	--no-browser --no-mathjax --ip=* --port $PORT \
	--config=jupyterconfig.py notebooks